# Generated by Django 3.2.5 on 2023-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_session_warnings_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='theory_answer',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('M', 'Multiple Choice'), ('T', 'Theory')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_A',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_B',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_C',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_D',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
