# Generated by Django 3.2.5 on 2023-10-20 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230412_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='no_of_questions',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of questions'),
        ),
    ]
